<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="10" tests="40" name="Test" time="59.2" errors="0" timestamp="2024-08-26T13:35:59 IST">
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="2.524">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.512">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.402">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.381">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.395">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.25">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.185">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.282">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.224">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.272">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.247">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.332">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.31">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.375">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.33">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.493">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.193">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.208">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.461">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.GetUserInfoTest" name="getUserInfo" time="1.428">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429],
	expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429],
expected [200] but found [429]
at apiTestCases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.469">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.441">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.209">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.265">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;error&amp;quot; (class pojo.UserDetails), not marked as ignorable (3 known properties: &amp;quot;name&amp;quot;, &amp;quot;count&amp;quot;, &amp;quot;age&amp;quot;])
 at [Source: (String)&amp;quot;{&amp;quot;error&amp;quot;:&amp;quot;Request limit reached&amp;quot;}&amp;quot;; line: 1, column: 11] (through reference chain: pojo.UserDetails[&amp;quot;error&amp;quot;])">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:229)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
at helpers.GetUserInfoAPI.ValidateUserInfo(GetUserInfoAPI.java:37)
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:23)
... 28 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
... 39 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.328">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.483">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.386">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.183">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;error&amp;quot; (class pojo.UserDetails), not marked as ignorable (3 known properties: &amp;quot;name&amp;quot;, &amp;quot;count&amp;quot;, &amp;quot;age&amp;quot;])
 at [Source: (String)&amp;quot;{&amp;quot;error&amp;quot;:&amp;quot;Request limit reached&amp;quot;}&amp;quot;; line: 1, column: 11] (through reference chain: pojo.UserDetails[&amp;quot;error&amp;quot;])">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:229)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
at helpers.GetUserInfoAPI.ValidateUserInfo(GetUserInfoAPI.java:37)
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:23)
... 28 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
... 39 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.396">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.344">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.276">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.377">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;error&amp;quot; (class pojo.UserDetails), not marked as ignorable (3 known properties: &amp;quot;name&amp;quot;, &amp;quot;count&amp;quot;, &amp;quot;age&amp;quot;])
 at [Source: (String)&amp;quot;{&amp;quot;error&amp;quot;:&amp;quot;Request limit reached&amp;quot;}&amp;quot;; line: 1, column: 11] (through reference chain: pojo.UserDetails[&amp;quot;error&amp;quot;])">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:229)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
at helpers.GetUserInfoAPI.ValidateUserInfo(GetUserInfoAPI.java:37)
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:23)
... 28 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
... 39 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.446">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.418">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.34">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.243">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;error&amp;quot; (class pojo.UserDetails), not marked as ignorable (3 known properties: &amp;quot;name&amp;quot;, &amp;quot;count&amp;quot;, &amp;quot;age&amp;quot;])
 at [Source: (String)&amp;quot;{&amp;quot;error&amp;quot;:&amp;quot;Request limit reached&amp;quot;}&amp;quot;; line: 1, column: 11] (through reference chain: pojo.UserDetails[&amp;quot;error&amp;quot;])">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:229)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
at helpers.GetUserInfoAPI.ValidateUserInfo(GetUserInfoAPI.java:37)
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:23)
... 28 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
... 39 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.208">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.358">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.355">
    <skipped/>
  </testcase> <!-- validateUserInfoTest -->
  <testcase classname="apiTestCases.ValidateUserInfoTest" name="validateUserInfoTest" time="1.281">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &amp;quot;error&amp;quot; (class pojo.UserDetails), not marked as ignorable (3 known properties: &amp;quot;name&amp;quot;, &amp;quot;count&amp;quot;, &amp;quot;age&amp;quot;])
 at [Source: (String)&amp;quot;{&amp;quot;error&amp;quot;:&amp;quot;Request limit reached&amp;quot;}&amp;quot;; line: 1, column: 11] (through reference chain: pojo.UserDetails[&amp;quot;error&amp;quot;])">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:30)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:229)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
at helpers.GetUserInfoAPI.ValidateUserInfo(GetUserInfoAPI.java:37)
at apiTestCases.ValidateUserInfoTest.validateUserInfoTest(ValidateUserInfoTest.java:23)
... 27 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class pojo.UserDetails), not marked as ignorable (3 known properties: "name", "count", "age"])
 at [Source: (String)"{"error":"Request limit reached"}"; line: 1, column: 11] (through reference chain: pojo.UserDetails["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.java:28)
... 38 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- validateUserInfoTest -->
</testsuite> <!-- Test -->
